"""
scripts/seed_neon_db.py
-----------------------
Seeds Neon PostgreSQL from the four JSON files in data/:
  companies.json            → companies table
  skills.json               → skills table
  job_cache.json            → job_cache table
  market_insight_snapshots.json → market_insight_caches table

Run from the backend/ directory:
    python scripts/seed_neon_db.py

Requires the DATABASE_URL env var to point to Neon.
"""

import json
import logging
import sys
from copy import deepcopy
from pathlib import Path
from datetime import datetime, timedelta, timezone

# ── Path bootstrap ─────────────────────────────────────────────────────────────
_BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_BACKEND_ROOT))

from sqlalchemy import select, text
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.core.database import db_session, verify_connection
from app.models.models import Company, JobCache, Skill, MarketInsightCache

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(levelname)-8s | %(message)s")
log = logging.getLogger("seed_neon")

DATA_DIR = _BACKEND_ROOT.parent / "data"


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_json(filename: str) -> list:
    path = DATA_DIR / filename
    if not path.exists():
        log.error(f"File not found: {path}")
        return []
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    log.info(f"Loaded {len(data)} records from {filename}")
    return data


def strip_keys(records: list, keys_to_remove: list) -> list:
    """Return a new list of dicts with specified keys removed."""
    cleaned = []
    for r in records:
        row = deepcopy(r)
        for k in keys_to_remove:
            row.pop(k, None)
        cleaned.append(row)
    return cleaned


# ── Seeders ───────────────────────────────────────────────────────────────────

def seed_companies(db, raw: list) -> int:
    """
    Insert companies. The JSON has: id, name, logo_url, industry.
    We strip 'id' (auto-generated by DB) and insert the rest.
    Conflict target: unique column 'name'.
    """
    if not raw:
        log.warning("companies.json is empty — skipping.")
        return 0

    rows = strip_keys(raw, ["id"])
    stmt = pg_insert(Company).values(rows)
    stmt = stmt.on_conflict_do_nothing(index_elements=["name"])
    db.execute(stmt)
    db.commit()
    log.info(f"✓  companies: {len(rows)} rows processed (skips duplicates).")
    return len(rows)


def seed_skills(db, raw: list) -> int:
    """
    Insert skills. The JSON has: id, name, category, is_trending, demand_score.
    We strip 'id' and insert the rest.
    Conflict target: unique column 'name'.
    """
    if not raw:
        log.warning("skills.json is empty — skipping.")
        return 0

    rows = strip_keys(raw, ["id"])
    stmt = pg_insert(Skill).values(rows)
    stmt = stmt.on_conflict_do_nothing(index_elements=["name"])
    db.execute(stmt)
    db.commit()
    log.info(f"✓  skills: {len(rows)} rows processed (skips duplicates).")
    return len(rows)


def seed_jobs(db, raw: list) -> int:
    """
    Insert job_cache rows. The JSON has:
      id, title, company, company_id, location, salary_min, salary_max,
      skills_required (list), is_active, source.

    We:
      1. Strip 'id' (auto-generated by DB).
      2. Add 'external_id'  = f"seed-{original_id}" (required by model unique constraint).
      3. Add 'posted_at'    = now() if missing.
      4. Add 'is_remote'    = False if missing.
      5. Add 'job_type'     = 'full_time' if missing.
      6. Add 'experience_level' = 'entry' if missing.

    Conflict target: (source, external_id).
    """
    if not raw:
        log.warning("job_cache.json is empty — skipping.")
        return 0

    now = datetime.now(timezone.utc)
    rows = []
    for job in raw:
        row = deepcopy(job)
        original_id = row.pop("id", None)          # remove auto-PK conflict
        row.setdefault("external_id", f"seed-{original_id}" if original_id else f"seed-{len(rows)}")
        row.setdefault("posted_at", now)
        row.setdefault("is_remote", False)
        row.setdefault("job_type", "full_time")
        row.setdefault("experience_level", "entry")
        row.setdefault("salary_currency", "INR")
        rows.append(row)

    stmt = pg_insert(JobCache).values(rows)
    stmt = stmt.on_conflict_do_nothing(index_elements=["source", "external_id"])
    db.execute(stmt)
    db.commit()
    log.info(f"✓  job_cache: {len(rows)} rows processed (skips duplicates).")
    return len(rows)


def seed_insights(db, raw: list) -> int:
    """
    Insert market_insight_caches rows.
    Each JSON record has:
      id, role_type, location, salary_min, salary_median, salary_max,
      top_skills, salary_trend.

    We map each record to a MarketInsightCache row:
      insight_type = 'role_overview'
      parameters   = {role_type, location}
      data         = everything else (all the numbers + arrays)
      expires_at   = now + 90 days

    No hard unique constraint on parameters, so we check if ANY rows exist
    for this role_type+location before inserting to avoid duplicates on reruns.
    """
    if not raw:
        log.warning("market_insight_snapshots.json is empty — skipping.")
        return 0

    now = datetime.now(timezone.utc)
    inserted = 0

    for item in raw:
        role_type = item.get("role_type")
        location  = item.get("location")

        # Idempotency check — skip if this combo already exists
        existing = db.execute(
            select(MarketInsightCache).where(
                MarketInsightCache.insight_type == "role_overview",
                MarketInsightCache.parameters["role_type"].astext == role_type,
                MarketInsightCache.parameters["location"].astext == location,
            )
        ).scalars().first()

        if existing:
            log.debug(f"  Skip (exists): {role_type} / {location}")
            continue

        payload = {k: v for k, v in item.items() if k not in ("id", "role_type", "location")}
        row = MarketInsightCache(
            insight_type="role_overview",
            parameters={"role_type": role_type, "location": location},
            data=payload,
            generated_at=now,
            expires_at=now + timedelta(days=90),
        )
        db.add(row)
        inserted += 1

    db.commit()
    log.info(f"✓  market_insight_caches: {inserted} new rows inserted (skipped existing).")
    return inserted


# ── Main ──────────────────────────────────────────────────────────────────────

def seed_all():
    log.info("=" * 60)
    log.info("  JobFor — Neon DB Seeder")
    log.info(f"  Data directory: {DATA_DIR}")
    log.info("=" * 60)

    # Test connection
    if not verify_connection():
        log.critical("Cannot connect to PostgreSQL. Check DATABASE_URL in .env")
        sys.exit(1)
    log.info("Connected to Neon PostgreSQL ✓")

    # Load JSON files
    companies_data = load_json("companies.json")
    skills_data    = load_json("skills.json")
    jobs_data      = load_json("job_cache.json")
    insights_data  = load_json("market_insight_snapshots.json")

    totals = {}

    with db_session() as db:
        # 1. Companies (no FK deps)
        log.info("\n── Seeding companies ──")
        totals["companies"] = seed_companies(db, companies_data)

        # 2. Skills (no FK deps)
        log.info("\n── Seeding skills ──")
        totals["skills"] = seed_skills(db, skills_data)

        # 3. Jobs (FK: company_id → companies — already inserted above)
        log.info("\n── Seeding job_cache ──")
        totals["jobs"] = seed_jobs(db, jobs_data)

        # 4. Market Insights (no FK deps)
        log.info("\n── Seeding market_insight_caches ──")
        totals["insights"] = seed_insights(db, insights_data)

    log.info("\n" + "=" * 60)
    log.info("  Seeding complete!")
    log.info(f"  companies          : {totals['companies']} records")
    log.info(f"  skills             : {totals['skills']} records")
    log.info(f"  job_cache          : {totals['jobs']} records")
    log.info(f"  market_insights    : {totals['insights']} records")
    log.info("=" * 60)


if __name__ == "__main__":
    seed_all()
